### ISSUE TITLE
Error: invalid http method

### ISSUE THREAD

**Issue by NotAFile** [matrix-org/pantalaimon#12]
```
Error handling request
Traceback (most recent call last):
  File "/home/nota/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

When using gomuks.

**Comment by poljar** [comment]
Is this perhaps an instance of this https://github.com/aio-libs/aiohttp/issues/3287?

Is there any more info? What did you try to do with gomuks? Could you snoop out what request gomuks sends out?

**Comment by NotAFile** [comment]
Turns out the problem was trying to connect to the server via https://, which I'd forgotten to correct in my config. Better errors could be provided though, I guess?

**Comment by poljar** [comment]
Oh, ok.

I guess but where would the error be? The client does get a 400 response, no?

**Comment by NotAFile** [comment]
I'm pretty sure this is really an aiohttp issue. I don't think there's anything you can do to catch this error.

**Comment by dillfrescott** [comment]
Still getting this error and have no idea how to fix it.

**Comment by dillfrescott** [comment]
When i try to use http it says its not a valid homeserver
