### ISSUE TITLE
[panctl] fails to accept passwords with spaces 

### ISSUE THREAD

**Issue by rmNULL** [matrix-org/pantalaimon#138]
**Describe the bug**
When Passing passphrase to import-keys only the first
word is taken. This also happens with export-keys
passphrase.

**To Reproduce**
* panctl
* `import-keys username /tmp/path-to-key a lengthy password`
> Error: unrecognized arguments: lengthy password' (see help)

**Expected behavior**
The whole password should be considered.
It doesn't work with quotes too.

**Screenshots**
![#1663490039-scap](https://user-images.githubusercontent.com/8173131/190893292-2e6e8376-3d45-4a9f-b464-64ef11af8ca6.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux 5.18.9_1
 - Browser: N/A
 - Version: panctl 0.10.4

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
I suspect this issue is caused by [result.split() before passing the line to parser](https://github.com/matrix-org/pantalaimon/blob/6b7b87bb6a0f4cd341e2b9ae0d5d94c7aa317dd5/pantalaimon/panctl.py#L592).
I was thinking maybe we could handle quoted input like shell
does and perform split based on that rather than just
spaces. I'm willing to perform these changes, but wanted
to get a go signal before taking up this task.

**Comment by chookity-pokk** [comment]
This is fixed with #185
