### ISSUE TITLE
Pantalaimon returning Invalid Media IDs tokens

### ISSUE THREAD

**Issue by xenomorph1096** [matrix-org/pantalaimon#141]
I am trying to use Pantalaimon for using the ement client from Emacs with my encrypted matrix rooms. 

For some reason, Whenever I receive an image in a room from someone else, I am unable to open this image.

The link for the image that is given to me in ement is something like this: `http://127.0.0.1:8009/_matrix/media/r0/download/matrix.org/<mediaid>` . (Pantalaimon runs at http://127.0.0.1:8009)

The response from the Pantalaimon daemon is: `{"errcode":"M_UNKNOWN","error":"Invalid media id token [b'', b'matrix.org', b'<mediad>']"}`

I can confirm that the media id is not incorrect, since `http://matrix.org/_matrix/media/r0/download/matrix.org/<mediaid>` definitely downloads an encrypted file. 

It seems that Pantalaimon is not syncing the file from my matrix.org homeserver.

I am running the default systemd configuration file on Archlinux.

**Comment by salehmu** [comment]
Same issue here. OS: Archlinux

**Comment by xenomorph1096** [comment]
Hey! thanks a lot for fixing this.
