### ISSUE TITLE
Mark as Deprecated.

### ISSUE THREAD

**Issue by FSG-Cat** [matrix-org/pantalaimon#167]
According to Travis R this should have been done aprox 2 years ago if we consult https://matrix.to/#/!dSMpkVKGgQHlgBDSpo:matrix.org/$UqrKahZfwlaksui7lMhcszFj6bLlv-J2Waha82cBnkk?via=matrix.org&via=envs.net&via=element.io so it might be a good idea to get around to it.

**Comment by poljar** [comment]
Duplicate of #168
