### ISSUE TITLE
Repository should have a deprecation notice on top of the readme

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/pantalaimon#168]
The repo is clearly inactive. Additionally, it pins nio to a version range from end of 2022. Now libolm is also deprecated. Meaning this a) runs on libolm and b) likely on an old version of libolm.

This is _potentially_ a security concern. Instead, it should be officially stated that people should a) migrate away from pantalaimon and b) not make new implementations on top of this :)

**Comment by TheArcaneBrony** [comment]
Do we have any known replacements?

**Comment by MTRNord** [comment]
> Do we have any known replacements?

from my understanding the replacement one should use is a native in-app implementation.

**Comment by TheArcaneBrony** [comment]
So, I have no replacement for pantalaimon as I don't *have* an in-app implementaiton.

**Comment by poljar** [comment]
Hank Greenburg has forked this repository and is maintaining it. They have asked if they could take over maintainership in this repo instead of maintaining a fork.

If people are fine with this, I would say that this would be a way forward.

**Comment by poljar** [comment]
It's over here: https://gitlab.com/greenbeast/pantalaimon/

**Comment by poljar** [comment]
Alright, since nobody complained I added @chookity-pokk as a maintainer. I think we can close this now.
