### ISSUE TITLE
PyGobject isn't fully optional.

### ISSUE THREAD

**Issue by poljar** [matrix-org/pantalaimon#26]
Under some systems the check if UI support is installed doesn't work correctly. PyGobject seems to be still fully required on such systems.

**Comment by non-Jedi** [comment]
Just ran into this. The issue with [the check in question](https://github.com/matrix-org/pantalaimon/blob/6b4f958d53090aac1f1102c4d6386b7497122faa/pantalaimon/ui.py#L18) uses `util.find_spec("gi.repository")` which checks for the `repository` submodule while assuming that the `gi` module will be able to be found. Simple fix is to just make it:

```python
utilfind_spec("gi") is not None and util.find_spec("gi.repository") is not None and util.find_spec("pydbus") is not None
```
