### ISSUE TITLE
After initial SendRetryError, each subsequent send_message() also fails with the same error

### ISSUE THREAD

**Issue by Randshot** [matrix-org/pantalaimon#38]
I don't really have any logs for this, since the error was catched by my bot.

Because I have a hard time reproducing this error reliably, I haven't figured out what caused the initial error yet, but it's possible that it was just a [normal error](https://github.com/poljar/matrix-nio/blob/master/nio/client/async_client.py#L1074) after the client failed to fully sync the room's state before the retry counter ran out.

The subsequent errors are also a mystery for now, but restarting the bot itself didn't help, so it must either be pantalaimon, or the underlying client (matrix-nio), that is causing this issue.

**Update:** I also just noticed that the subsequent errors only happen for the client/bot that encountered the initial error. I have 2 bots using pantalaimon at the same time, but the other one is still able to send messages after the first one encountered the error.

**Update 2:** I just noticed that the repeated errors are limited to the room that initially caused the error. If I try to send messages to other rooms, it still works. Maybe this is to be expected, but I thought I would mention it anyway.

**Comment by poljar** [comment]
Were the two bots using differing accounts? If so they are using separate nio clients, meaning it makes sense that they don't fail both.

**Comment by Randshot** [comment]
Yes, they were using different accounts. Just thought that may be worth mentioning. 🤷‍♂ 
I haven't encountered the error in the past day, after switching away from the docker container. Don't know whether that affected anything.

**Comment by Randshot** [comment]
Updated my initial post with new information.

**Comment by poljar** [comment]
Thanks, that's interesting. Maybe something odd with the room state. 🤔

**Comment by poljar** [comment]
There have been changes to how group sessions are shared, the error is hopefully gone. If it still fails or in some different way please feel free to reopen.
