### ISSUE TITLE
Installation procedure and PyPi package

### ISSUE THREAD

**Issue by almereyda** [matrix-org/pantalaimon#4]
Currently the Python Package Index PyPi does not contain a `pantalaimon` package.

For easy of installation with `pip3 install --user pantalaimon`, or similar, it could be considered to submit this repository as a package there.

**Comment by almereyda** [comment]
Currently `python3 setup.py install --user` is an affordable choice, too.

**Comment by poljar** [comment]
This is blocking on https://github.com/poljar/matrix-nio/issues/7. And that one is blocking on having python-olm on pypi.

**Comment by ara4n** [comment]
@almereyda pantalaimon is *very* young and not yet ready for anything but experimentation.  That said, we should fix the installation so that it works (whether that's by pypi or setup.py).

For the record, here are the hoops I went through to get it to build on macOS a few days ago:

```
# for olm
# remove -D from install in olm's Makefile as macOS doesn't support it
make
make install PREFIX=$HOME/olm

# for pantalaimon
virtualenv -p python3 env
. env/bin/activate
export CFLAGS=-I$HOME/olm/include
export LDFLAGS=-L$HOME/olm/lib
pip install "matrix-nio@ git+https://github.com/poljar/matrix-nio.git@async#egg=matrix-nio-0"
python setup.py install # to grab other deps

cd build
ln -s $OLM/build/libolm.dylib.3.0.0
cd ..

pantalaimon/daemon.py
```

The important line is the fairly magic `pip install "matrix-nio@ git+https://github.com/poljar/matrix-nio.git@async#egg=matrix-nio-0"` one.

**Comment by almereyda** [comment]
Pardon me for dropping the latest issues this frequently. I have simply followed the *This week in Matrix* pointer and were eager to get this code running. This is much easier for others with more complete documentation, may it be in README, docs or the issues here.

**Comment by poljar** [comment]
Fixed: https://pypi.org/project/pantalaimon/

**Comment by toger5** [comment]
I tried the `pip3 --user install pantalaimon` but it fails:
``` gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/name/Projects/olm/build/ -I/usr/include/python3.7m -c build/temp.linux-x86_64-3.7/_libolm.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_libolm.o -I../include
    build/temp.linux-x86_64-3.7/_libolm.c:22:12: fatal error: pyconfig.h: No such file or directory
       22 | #  include <pyconfig.h>
          |            ^~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ndx0_czw/python-olm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -I/home/name/Projects/olm/build/ install --record /tmp/pip-record-aa93qyp6/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-ndx0_czw/python-olm/

```
I compiled olm from source. And tried:
`pip3 install --user --global-option=build_ext --global-option="-I/home/name/Projects/olm/build/" pantalaimon`

**Comment by poljar** [comment]
You need the python development headers. They may be found in a package called python-dev for your distribution. We should probably add that to the readme.
