### ISSUE TITLE
Fractal completely bypasses pantalaimon

### ISSUE THREAD

**Issue by symphorien** [matrix-org/pantalaimon#40]
### Steps to reproduce:
* Configure pantalaimon as follows:
```
[local]
HomeServer = https://matrix.org
```
* Start pantalaimon:
```
$  pantalaimon --log-level debug
======== Starting daemon for homeserver local on http://127.0.0.1:8009 ========
(Press CTRL+C to quit)
```
* Start fractal, indicate `http://localhost:8009` and log in to a matrix.org account

### Expected outcome
* Pantalaimon logs something
* Fractal can decrypt messages
* pantalaimon appears in my list of devices

### Actual outcome
* Pantalaimon does not log anything
* Fractal does not see encrypted messages
* pantalaimon does not appear in my list of devices
* clicking on account parameters shows "homeserver: https://matrix-client.matrix.org"

As if Fractal completely bypassed pantalaimon.

Note that logging in with spectral does trigger the expected behavior above.

### Version information:
pantalaimon: version 0.4
fractal: 4.2.2
spectral: 817

**Comment by turt2live** [comment]
Pantalaimon probably needs to strip the well_known data off the login response to avoid Fractal changing homeserver URLs.

**Comment by poljar** [comment]
Since no device was created I suspect something else is going on. But yes, we should do that as well.

**Comment by poljar** [comment]
Seems like fractal does a `http://localhost:8008/.well-known/matrix/client` regardless of what was provided to it, a homeserver or a non-full mxid for the login.

**Comment by poljar** [comment]
Fix is provided here https://github.com/matrix-org/pantalaimon/commit/45b823eac6631d9a06ae2529d3167ce88aebd0cc.

POST is overridden as well since Fractal somehow manages to get valid info using a POST request. Fix for this has been posted upstream [here](https://gitlab.gnome.org/GNOME/fractal/merge_requests/521).

@symphorien if you could test the patch and confirm that it works, that would be great.

**Comment by symphorien** [comment]
I confirm the patch fixes the issue. Thanks!

**Comment by poljar** [comment]
Fixed by https://github.com/matrix-org/pantalaimon/commit/45b823eac6631d9a06ae2529d3167ce88aebd0cc.

Thanks for testing.
