### ISSUE TITLE
Message edited in encrypted room becomes fallback edit

### ISSUE THREAD

**Issue by MRAAGH** [matrix-org/pantalaimon#44]
Reproduced with gomuks + pantalaimon:

1. Edit a message in gomuks in an encrypted room:
![Screenshot_2020-04-04_20-46-10](https://user-images.githubusercontent.com/33424247/78459012-427f8400-76b6-11ea-9b46-d7bda5f5412a.png)

2. Look at this message in an e2e client (without pantalaimon):
![Screenshot_2020-04-04_20-53-48](https://user-images.githubusercontent.com/33424247/78459027-68a52400-76b6-11ea-8936-ca7711cd7b44.png)

Notice that the fallback was used. This only happens in encrypted rooms.

**Comment by poljar** [comment]
Fixed by https://github.com/poljar/matrix-nio/commit/d4d1ce6a7373e140056a2cde7db3b4fce2f745b2
