### ISSUE TITLE
Janus 0.5 is incompatible with us.

### ISSUE THREAD

**Issue by poljar** [matrix-org/pantalaimon#49]
Janus 0.5 removed the loop argument when creating a queue. The loop argument will be removed from python 3.10 as well.

We will need to rework our startup logic so it runs inside a async function. This is a bit annoying since workarounds are needed for click to work this way as well.

**Comment by r3k2** [comment]
pantalaimon is broken on my system cant run gomuks now because of this.. :(  another reason for clients to have their e2ee build in,

**Comment by poljar** [comment]
You can just keep on using Janus 0.4. This will get fixed soonish.

**Comment by r3k2** [comment]
@poljar yeah pain in the ass..
For those who need to downgrade and are in Arch and do not like to infect the system with pip libs and have a "clean" setup manage by the distribution(pacman/yay) follow directions below:
```
download 
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-janus
edit and change:
pkgver=0.4.0
and sha256sums to:
sha256sum janus-0.4.0.tar.gz
cfc221683160b91b35bae1917e2957b78dad10a2e634f4f8ed119ed72e2a88ef  janus-0.4.0.tar.gz
run
makepkg -s
run:
yay -U python-janus-0.4.0-1-any.pkg.tar.xz
```

**Comment by poljar** [comment]
The AUR is a git repo, you can get to the old PKGBUILD [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-janus&id=7599ad5aeda0ddd211c30d3415726fc9d168875a).
