### ISSUE TITLE
matrix-nio dependency does not build with setup.py install

### ISSUE THREAD

**Issue by almereyda** [matrix-org/pantalaimon#5]
When running `python setup.py install --user`, the `matrix-nio` dependency cannot be resolved.

```
Processing dependencies for pantalaimon==0.1
Searching for matrix-nio@ git+https://github.com/poljar/matrix-nio.git@async#egg=matrix-nio-0
Reading https://pypi.org/simple/matrix-nio/
Couldn't find index page for 'matrix-nio' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for matrix-nio@ git+https://github.com/poljar/matrix-nio.git@async#egg=matrix-nio-0
error: Could not find suitable distribution for Requirement.parse('matrix-nio@ git+https://github.com/poljar/matrix-nio.git@async#egg=matrix-nio-0')
```

From https://github.com/poljar/matrix-nio/blob/master/setup.py#L27 we also learn to try to get https://github.com/poljar/python-olm installed, which depends on https://git.matrix.org/git/olm/about/

To document a working course of action, one clones `olm` and builds it with

```
cmake . -Bbuild
cmake --build build
cd build
sudo make install
```

Then `python-olm` and `matrix-nio` build happily during `python3 setup.py install --user`.

This also relates to #4.

**Comment by poljar** [comment]
I believe that there's now sufficient warning in the README that libolm is required.
