### ISSUE TITLE
Can't send messages

### ISSUE THREAD

**Issue by ChristianPauly** [matrix-org/pantalaimon#55]
Hey, thank you for your awesome work with this tool. I'm trying to implement this into the [Qml version of FluffyChat for Ubuntu Touch](https://gitlab.com/ChristianPauly/fluffychat). I can login, sync and decrypt messages but something is wrong with sending messages.

When sending messages in an encrypted room (in unencrypted its working fine) I send for example this:
```
[PUT] 
/client/r0/rooms/!MlSuBbJLzKITNqowdb:tchncs.de/send/m.room.message/1592559364500
{"body":"7","msgtype":"m.text"}
```

With headers:
```
'Content-Type', 'application/json'
'Authorization', 'Bearer ' + token
```

But on Pantalaimon log-level debug side there is nothing and I never get a response.
Maybe you have an idea what I'm doing wrong here?

**Comment by poljar** [comment]
I think that's because the room contains unverified devices. 

In the default configuration Pantalaimon won't let you send messages to a room unless all devices are verified, you can switch off verification in the config or you can verify the devices using Pantalaimon.

**Comment by ChristianPauly** [comment]
Yes that was it!

IgnoreVerification = True

And it works. Thank you very much :-)
Next step will be to implement a GUI for the verification step.
