### ISSUE TITLE
Messages sent unencrypted

### ISSUE THREAD

**Issue by browserdotsys** [matrix-org/pantalaimon#56]
I'm trying to use pantalaimon to send messages to an E2E encrypted room. After logging in, getting an access token, and verifying the device through `panctl`, I try to send a message to an E2E room:

```
curl --header "Authorization: Bearer $MATRIX_TOKEN" -XPOST -d '{"msgtype":"m.text", "body":"pantalaimon testing for bug report"}' "http://localhost:8008/_matrix/client/r0/rooms/$ROOM/send/m.room.message"
```

But the message appears to end up unencrypted:

![image](https://user-images.githubusercontent.com/45294114/85239383-1ba13600-b3f9-11ea-8fd9-79457626006b.png)

Config:

```
[Default]
LogLevel = Debug
SSL = True
Notifications = On

[local-matrix]
Homeserver = https://matrix.example.com
ListenAddress = localhost
ListenPort = 8008
IgnoreVerification = True
```

Versions:

```
$ pip3.8 list | grep python-olm
python-olm                                        3.1.3  
$ pip3.8 list | grep nio
matrix-nio                                        0.13.0 
$ pip3.8 list | grep pantalaimon
pantalaimon                                       0.6.4  
```

Debug log (user and room names redacted):
[debug.log](https://github.com/matrix-org/pantalaimon/files/4810665/debug.log)

**Comment by poljar** [comment]
As the commit explains, you're using `POST` instead of `PUT` to send the message, this is not in the spec but Synapse allows it for some reason. Fixed in master.
