### ISSUE TITLE
matrix-nio is overly constrained; needs updating again

### ISSUE THREAD

**Issue by colemickens** [matrix-org/pantalaimon#58]
This needs to be done again. Can you make it `>=0.14 <0.15` to allow bugfixes? This is a bit annoying to coordinate as someone trying to package something that needs a newer `matrix-nio` but also can't break `pantalaimon`. Thanks!

**Comment by poljar** [comment]
Hopefully fixed in the latest release.

**Comment by symphorien** [comment]
Is it possible to release a new version of pantalaimon compatible avec matrix-nio 1.15 ?

**Comment by poljar** [comment]
It is, I'll do a pan release this week.

**Comment by poljar** [comment]
Sorry for the delay, we had another nio bugfix release but it's out now.
