### ISSUE TITLE
can you import keys?

### ISSUE THREAD

**Issue by ReK2Fernandez** [matrix-org/pantalaimon#7]
I have more than 500 keys from my current weechat with matrix plugin install and riot-desktop to be able to test this proxy I will like to be able to import the keys so I do not have to accept then again... way to many

**Comment by poljar** [comment]
Not yet, the project is only a week old and is just a initial working prototype. But key imports/exports are a planed feature.

**Comment by ReK2Fernandez** [comment]
@poljar hey I know you :) how many projects are you in? :D :dancer:  this was only to be able to try gomuks into they add olm support. I been using weechat in the mean time. but will rather a GO app.

**Comment by poljar** [comment]
Hi @ReK2Fernandez. It's rapidly going into the too many category :). You'll have to be a little bit patient since this project just started. Also gomuks might have its own problems.

**Comment by poljar** [comment]
This is now supported.
