### ISSUE TITLE
How to use maubot with pantalaimon?

### ISSUE THREAD

**Issue by johnygum** [matrix-org/pantalaimon#77]
Hi,
I want to use maubot for my encrypted rooms with pantalaimon, but I get stuck at:
`WARNING: pantalaimon: User @user:matrix.org doesn't have a matching pan client.`

I am running both pantaliamon and maubot in Docker.

I found issue #54, but when I tried to log in through pantalaimon: `docker exec -it pantalaimon panctl` I got the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/panctl", line 5, in <module>
    from pantalaimon.panctl import main
  File "/usr/local/lib/python3.8/site-packages/pantalaimon/panctl.py", line 26, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
```

Thanks for your help!

**Comment by poljar** [comment]
You'll have to log in through pantalaimon at least once with a given server/user pair for it to start working. More detail can be found here on why that's needed https://github.com/matrix-org/pantalaimon/issues/14.

**Comment by johnygum** [comment]
Thanks for your help! I didn't quite understand what was meant by logging in through panatalaimon. I logged in with [`matrix-commander`](https://github.com/8go/matrix-commander) and now it is working!

**Comment by aspacca** [comment]
> You'll have to log in through pantalaimon at least once with a given server/user pair for it to start working. More detail can be found here on why that's needed #14.

a comma is missing in setup.py preventing to install `prompt_toolkit`
https://github.com/matrix-org/pantalaimon/blob/master/setup.py#L29

I've also created a custom docker file related to https://github.com/matrix-org/pantalaimon/issues/37#issuecomment-630890139
https://gist.github.com/aspacca/7ba0e4585cfda0ca8857d10a7e9b5e85

**Comment by poljar** [comment]
Thanks, comma has been added.

If you think it makes sense, feel free to open a PR to include this docker file in the repo as well.

**Comment by mackiexx** [comment]
> pantalaimon panctl

How do you login through pantalaimon, i am experiencing same issue

**Comment by mackiexx** [comment]
> You'll have to log in through pantalaimon at least once with a given server/user pair for it to start working. More detail can be found here on why that's needed #14.

i have logged in using the client api like this 

curl -XPOST -d '{"type":"m.login.password", "user":"user", "password":"password"}' "https://host.com/_matrix/client/r0/login"

Why is it still not working, how do they login to daemon? there is no docs anywhere to explain this
