### ISSUE TITLE
errcode: 'M_UNKNOWN_TOKEN', error: 'Unrecognised access token.'

### ISSUE THREAD

**Issue by Loader009** [matrix-org/pantalaimon#78]
**Describe the bug**
I use pantalaimon for mjolnir, currently in an unencrypted room.
Whenever I run mjolnir with using pantalaimon in the configs, I get the error below.
This doesn't happen without pantalaimon, so I think the issue is here.
Also thanks to TravisR who pointed me on that.
Room version: 6

**To Reproduce**
Start mjolnir (while pantalaimon is running in the background) and the error appears without anything doing.

**Expected behavior**
Error shouldn't happen and mjolnir shouldn't panic.

**Server:**
ArchLinuxARM (arm64)
docker-compose version 1.27.4, build unknown
Docker version 19.03.13-ce, build 4484c46d9d

pantalaimon v0.8.0-1
mjolnir v0.1.16

**Additional context**
Please tell me if I forgot something.
I hope it's ok to put the logs in here and not in a separate file.
If not - just say so.

Error in Mjolnir:
```
[INFO] [MatrixLiteClient (REQ-6)] PUT http://pantalaimon:8008/_matrix/client/r0/rooms/!---HIDDEN---F%3Amatrix.org/send/m.room.message/1607898746183__REQ5
[DEBUG] [MatrixLiteClient (REQ-6)] body = {"body":"Mjolnir is starting up. Use !mjolnir to query status.","formatted_body":"Mjolnir is starting up. Use !mjolnir to query status.","msgtype":"m.notice","format":"org.matrix.custom.html"}
[DEBUG] [Metrics] matrix_client_function_call {
  functionName: 'getPublishedAlias',
  client: '<MatrixClient @---ACCOUNT---:matrix.org>',
  uniqueId: '1607898745998-10'
} 188
[DEBUG] [MatrixLiteClient (REQ-6 RESP-H401)] { errcode: 'M_UNKNOWN_TOKEN', error: 'Unrecognised access token.' }
[ERROR] [MatrixLiteClient (REQ-6)] { errcode: 'M_UNKNOWN_TOKEN', error: 'Unrecognised access token.' }
[DEBUG] [Metrics] matrix_client_function_call {
  functionName: 'doRequest',
  client: '<MatrixClient @---ACCOUNT---:matrix.org>',
  uniqueId: '1607898746183-16'
} 208
[DEBUG] [Metrics] matrix_client_function_call {
  functionName: 'sendEvent',
  client: '<MatrixClient @---ACCOUNT---:matrix.org>',
  uniqueId: '1607898746183-15'
} 209
[DEBUG] [Metrics] matrix_client_function_call {
  functionName: 'sendMessage',
  client: '<MatrixClient @---ACCOUNT---:matrix.org>',
  uniqueId: '1607898746183-14'
} 210
node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<IncomingMessage>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by poljar** [comment]
You'll need to log in at least once per user id through Pantalaimon for it to start working, the readme mentions this 
> Note that logging in to the daemon is required to start a sync loop for a user. After that clients can connect using any valid access token for the user that logged in. Multiple users per homeserver are supported.

And there is an issue about this open https://github.com/matrix-org/pantalaimon/issues/14.

**Comment by Loader009** [comment]
It works, I did it probably wrong the first time (I think I logged out and/or renamed the session or something else).

Thank you, at least others will find the problem with this error message.
I will close this as soon as I removed the building log (it makes this issue unnecessary bloated).
