### ISSUE TITLE
Thumbnails not generating for media uploaded in unencrypted rooms

### ISSUE THREAD

**Issue by Midek** [matrix-org/pantalaimon#90]
**Describe the bug**
After version 9.0, uploading pictures in unencrypted rooms results in an image that has no thumbnail visible for other users.
It seems to happen for pictures uploaded from every client i tested (gomuks, quickmedia, fractal).
Uploading pictures in encrypted rooms works fine.

**To Reproduce**
1. Use a matrix client without encryption and connect through pantalaimon
2. Upload an image
3. Element users cannot see the thumbnail

**Expected behavior**
Thumbnail being generated and displayed properly

**Screenshots**
![bug](https://midov.pl/smiecioweobrazki/pantsuloli.bug.png)

**Desktop (please complete the following information):**
 - OS: Arch GNU/Linux 5.11.6-zen1-1-zen
 - Version 0.9.2

**Comment by CortexPE** [comment]
Bump,

Can reproduce, using `pantalaimon v0.10.0` on a `Ubuntu 19.10` VPS running `x86_64 Linux 5.3.0-64-generic`, `matrix-bot-sdk v0.5.18` and the Element Web client as viewer

Video: 

https://user-images.githubusercontent.com/17762324/121777488-f0dd5e00-cbc4-11eb-942c-b8c68da6c8fa.mp4
